### ISSUE TITLE
How do you calculate the final mAP

### ISSUE THREAD

**Issue by Qingzhang1994** [aneeshan95/Sketch_LVM#12]
I ran the TUBerlin dataset and I trained the model using 4 Gpus to get the results in the image. Which of these results in the picture represents the final MAP
![image](https://github.com/aneeshan95/Sketch_LVM/assets/48178899/335b572b-9ed2-490a-b8c8-86b18faa72a3)

**Comment by x-28** [comment]
So which mAP value did you end up using?

**Comment by Qingzhang1994** [comment]
The calculation method of mAP given by the author is wrong, he only uses a small amount of data to calculate mAP, so the experimental result is very high.

**Comment by aneeshan95** [comment]
There's nothing wrong in the mAP evaluation code. Small amount of data is not used. What you're failing to understand is that this is designed for zero-shot retrieval on the harder split of 104:21  . That is why 21 classes are given for Sketchy.
Moreover only Sketchy evaluation setup is provided. The same for TUB is different and we do not take responsibility for your implementation of our code
