### ISSUE TITLE
When will the code be published?

### ISSUE THREAD

**Issue by cuoll** [aneeshan95/Sketch_LVM#3]
Hi, after reading the paper I feel that your work is very interesting, so I would like to ask when are you going to publish the code?

**Comment by aneeshan95** [comment]
Hello,
Thanks for your interest in our work. We have made a basic version of the code public for encouraging research purposes. Please consider that this is a basic implementation of the paper, not ideally optimised for performance. 
The code for the ZS-SBIR paradigm using CLIP has been uploaded now, and the code for the extension to FG-SBIR will be uploaded in some time. 
Hope you found this useful.
Thanks
