### ISSUE TITLE
 Could you tell me which part is the code of Patch Shuffling Loss?

### ISSUE THREAD

**Issue by Gary-code** [aneeshan95/Sketch_LVM#4]
Nice work in CVPR 2023. Could you tell me which part is the code of Patch Shuffling Loss?

**Comment by aneeshan95** [comment]
Hi Gary,
Thanks for your interest in our work. We have made a basic version of the code public for encouraging research purposes. Please consider that this is a basic implementation of the paper, not ideally optimised for performance. 
The code for the ZS-SBIR paradigm using CLIP has been uploaded now, and the code for the extension to FG-SBIR will be uploaded in some time. 
So, the code does not contain the Patch Shuffling Loss yet. 
Hope you found this useful.
Thanks
