### ISSUE TITLE
Nice work in CVPR 2023. Could you tell me the code of environment?

### ISSUE THREAD

**Issue by Qingzhang1994** [aneeshan95/Sketch_LVM#5]
Nice work in CVPR 2023. Could you tell me the code of environment?

When I run the program, there is a problem with the environment，Can you provide me with the code environment，like this？
![image](https://github.com/aneeshan95/Sketch_LVM/assets/48178899/60b0f096-10f9-4640-91a4-ea180bc4bf2b)
![image](https://github.com/aneeshan95/Sketch_LVM/assets/48178899/f1beae46-f4cf-4fbd-99d9-8a543db03300)

**Comment by aneeshan95** [comment]
We have uploaded the basic `environment.yml` file with the package specifications used for this project. Hope that helps.
