### ISSUE TITLE
Sketchy Dataset

### ISSUE THREAD

**Issue by finalyXG** [aneeshan95/Sketch_LVM#6]
Thank you for your wonderful work! I was wondering if you could provide some insight on how to access the extended Sketchy dataset mentioned in Section 6, which contains an additional 60,502 images. Additionally, it would be greatly appreciated if you could clarify whether any of the 21 unseen classes used for the zero-shot setup testing include images from this extra dataset mentioned in Section 6.

**Comment by Ferscery** [comment]
Hello, did you solve your problem? In addition, have you run his code, and did you get a result close to the text?

**Comment by finalyXG** [comment]
@Ferscery Still waiting for response:)

**Comment by aneeshan95** [comment]
Thanks for your interest in our paper.

1. The dataset split used is mentioned in the 'dataset' section in the paper. We use the split of 104/21 training/testing classes for our experiment. They are disjoint sets of data (photos not shared), where even the ImageNet pretrained classes are also absent from the testing set, hence the usage for zero-shot experiments.

2. As also mentioned in the readme file, please follow the instructions detailed in https://github.com/AnjanDutta/sem-pcyc/blob/master/download_datasets.sh to download the Sketchy-extended dataset.

**Comment by finalyXG** [comment]
Thank you so much for helpful the details!

**Comment by Qingzhang1994** [comment]
I have encountered this problem, I would like to ask you how to solve this problem, thank you for your answer
![image](https://github.com/aneeshan95/Sketch_LVM/assets/48178899/e21fdefc-63ae-4ae4-9ac2-fcd9c598e9e0)
![image](https://github.com/aneeshan95/Sketch_LVM/assets/48178899/7fbc77c2-a8f8-4d22-abcb-820ac38ae8ec)

**Comment by aneeshan95** [comment]
The fix for this has been uploaded.
Please use the newly uploaded code.
Thanks.

**Comment by Qingzhang1994** [comment]
Thanks

**Comment by Qingzhang1994** [comment]
![image](https://github.com/aneeshan95/Sketch_LVM/assets/48178899/5ba6d303-587a-4561-8de8-00e789db62cf)
get a result of Sketchy dataset

**Comment by Ferscery** [comment]
Hi, can you share the instructions you ran and
I would like to know roughly how long it takes to run

**Comment by Qingzhang1994** [comment]
python -m experiments.LN_prompt --exp_name=LN_prompt --n_prompts=3 --clip_LN_lr=1e-6 --prompt_lr=1e-4 --batch_size=128 --workers=64
![image](https://github.com/aneeshan95/Sketch_LVM/assets/48178899/c903f4ef-09be-41aa-a4de-3dbb1ea8a537)

Pretty fast
